### ISSUE TITLE
Does this work with FP 11+?

### ISSUE THREAD

**Issue by EddieOne** [lukebayes/asunit#17]
I see this repo hasn't been maintained for several years. I'm wondering if I would be safe to try this with Flash Player 11? Could be useful for the legacy programmers. :sob:

**Comment by lukebayes** [comment]
The [AsUnit 4.0 build](https://github.com/lukebayes/asunit/tree/master/asunit-4.0) was confirmed working with FP 10. If you're interested, go ahead and try it out. I'd happily accept Pull Requests if anything needs to be updated.

**Comment by EddieOne** [comment]
ok thanks
