### ISSUE TITLE
4.0.0 Needs to note dependancy on Flex SDK 

### ISSUE THREAD

**Issue by ghost** [lukebayes/asunit#2]
If you build 4.0.0 without the Flex SDK in your source path, you get an error:
1046: Type was not found or was not a compile-time constant: AsyncToken.

**Comment by lukebayes** [comment]
Thanks for posting this Issue! 

I'll get that pulled out, there shouldn't be forced SDK dependencies in there at all.

**Comment by lukebayes** [comment]
I just took a look, and there doesn't appear to be any references to AsyncToken in the AsUnit framework anywhere.

Can you provide more information?

Thanks,

Luke

**Comment by ghost** [comment]
Whoops, I sent you to the wrong place -- it's not 4.0.0, it's the tip of tree that has the issue. The contents of the downloadable 4.0.0 zip file are fine. 

In HEAD, the problem happens in AsychronousTestCase:

```
import mx.rpc.AsyncToken;
import mx.rpc.Responder;
import mx.rpc.events.FaultEvent;

/**
 * Extend this class if you have a TestCase that requires the
 * asynchronous load of external data.
 */
public class AsynchronousTestCase extends TestCase implements Test {
```

**Comment by lukebayes** [comment]
I just checked in a revision of AsyncTestCase that no longer references the mx packages. It looks like those were some utility methods that one of our contributors added and I missed. I created a new AyncHTTPServiceTestCase that has those helpers in there.

Thanks again for the catch!
