### ISSUE TITLE
SuiteRunner should reference interfaces instead of concrete classes for extensibility

### ISSUE THREAD

**Issue by ghost** [lukebayes/asunit#6]
protected var suiteRunner:SuiteRunner;
protected var testClasses:SuiteIterator;

should be...

protected var suiteRunner:IRunner;
protected var testClasses:Iterator;

**Comment by lukebayes** [comment]
I made that change in a local branch on this repo (http://github.com/patternpark/asunit) it should be posted shortly.

Don't be afraid to fork and make these edits in the future...

Thanks!

**Comment by lukebayes** [comment]
Sorry - URL got munged - meant this one:

http://github.com/patternpark/asunit

**Comment by ghost** [comment]
Thanks Luke,

Will fork it shortly; I'm writing an IntellijPrinter class that extends ASUnit4 to run and integrate with Intellij JUnit result console.

**Comment by lukebayes** [comment]
Nice! I'll get that patch pushed tomorrow night. My local build is kind of busted at the moment.
